ci: fix new link checker errors in PR builds
These errors seem to have been with us since February 28th, 2026, which
was when lychee 0.23.0 was used for the PR build for the first time:
https://github.com/git/git-scm.com/actions/runs/22511224516/job/65220662173#step:15:70

  [...]

  ### Errors in public/application.min.85d33c919f3ff9788e84d1be0d991a68627af6191d5d6ce65ac9a1216a11e585.css

  Error: * [ERROR] <error:> | Error building URL for
    "/images/bg/body.jpg" (Attribute: Some("url")): Cannot convert path
    '/images/bg/body.jpg' to a URI: To resolve root-relative links in local
    files, provide a root dir
  Error: * [ERROR] <error:> | Error building URL for
    "/images/bg/body.jpg" (Attribute: Some("url")): Cannot convert path
    '/images/bg/body.jpg' to a URI: To resolve root-relative links in local
    files, provide a root dir
  Error: * [ERROR] <error:> | Error building URL for
    "/images/bg/isometric-grid.png" (Attribute: Some("url")): Cannot convert
    path '/images/bg/isometric-grid.png' to a URI: To resolve root-relative
    links in local files, provide a root dir
  [...]

The preceding PR build succeeded on February 23rd, 2026:
https://github.com/git/git-scm.com/actions/runs/22313554003/job/64551960417#step:15:70
(it used lychee 0.21.0, still).

There haven't been any announcements of breaking changes in the 0.22.0
nor in the 0.23.0 release notes that would talk about `--root-dir` being
required (https://github.com/lycheeverse/lychee/releases), but it is now
obviously required.

This only affected the PR builds because we already use the `--root-dir`
option in the deployment pipeline (to work around issues stemming from
absolute URL path prefixes being required in forks).

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>